### PR TITLE
A Wireshark extcap plug-in for Sniffle

### PR DESCRIPTION
**Pull request by jaylogue**
Lately I've been using Sniffle quite a bit in a personal project I've been working on.  Since I like to use Wireshark, I decided to make Wireshark extcap plugin to allow me to launch Sniffle directly from within the GUI.  Lo and behold, I now see that there is a feature request (#38) asking for exactly this.  Hopefully this fits the bill.

Pretty much all of the options available in the sniff_receiver script are accessible via the GUI with the exception of the '--mac top' feature.  I wasn’t sure how useful that feature would be in this context.

I’ve also updated the README accordingly.

I've been using the plugin for a short while and so far it seems to be working well.  But it surely could do with some more testing.

### CODE REVIEW

**Comment by sultanqasim** [comment]
Ooh, nice. Thank you very much for implementing this. I'll try this out when I get a little time, maybe on Saturday.

**Comment by nono313** [comment]
@jaylogue Have you tried running in on a Windows instance of Wireshark ? I have copied all required files (looking at the cp command) in the extcap of my Wireshark install (C:\Program Files\Wireshark\extcap) but am not able to see the capture device after refresh.

With the exact same setup, running 'python ./sniff_receiver.py  -s COM8 -e -a -l' shows me advertisement packets.

**Comment by jaylogue** [comment]
I haven't tried on other platforms yet.  I wanted to see if the general thrust of this code was acceptable before investing more time.  I will investigate the Windows issue and update the PR accordingly.

**Comment by sultanqasim** [comment]
The general approach of this code looks good to me, and doesn't look like much of an additional effort to maintain feature parity with the rest of Sniffle. I still haven't gotten around to trying this out, but hopefully I'll find some time this week.

**Comment by jaylogue** [comment]
@sultanqasim Regarding code maintenance, I do note that there is a certain amount of duplication between the code in sniffle_extcap.py and sniff_receiver.py, particularly in the areas of argument parsing and capture setup.  One possible way to avoid this would be to extend sniffle_extcap.py to incorporate the functionality sniff_receiver.py, such that a single script could be used both in the context of Wireshark and from the command line.  In the latter case, I envision the command line interface would be identical to sniff_receiver.py, to maintain compatibility.

As I was writing sniffle_extcap.py I noted that this would be pretty easy to implement.  However I wanted to some feedback on the core Wireshark functionality before attempting this.

**Comment by nono313** [comment]
Thanks @jaylogue. I've just tested it. It works fine, I am able to see both of my LE Coded PHY advertising devices.

I do however have some issues where if I stop the scanning, Wireshark crashs without any error message.

**Comment by sultanqasim** [comment]
This hasn't been forgotten, I just need to get around to trying it :)

**Comment by sultanqasim** [comment]
Has the Windows extcap crash bug been fixed in upstream Wireshark? I don't normally use Windows, so I don't have everything set up to test.

**Comment by jaylogue** [comment]
> Has the Windows extcap crash bug been fixed in upstream Wireshark?

I have finally had time to look at this again, and unfortunately the crash is still present in current Wireshark (v3.6.5-0-g21f79ddbefbd).  I was able to capture a backtrace for the crash and have filed the following bug with the Wireshark project: [https://gitlab.com/wireshark/wireshark/-/issues/18093](https://gitlab.com/wireshark/wireshark/-/issues/18093).  If I have time, I may poke around in the source and see if I can come up with a fix.

**Comment by sultanqasim** [comment]
Thanks for looking into this. I'll rebase, experiment with, and merge this tonight or tomorrow.

**Comment by sultanqasim** [comment]
Actually working on rebasing and testing this now. Sorry about the delay. I want to include this in the Version 1.7 release.

**Comment by sultanqasim** [comment]
Cherry-picked/rebased in with some minor fixes and additions

**Pull request closed without merging**
